//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuần5
{
    /// <summary>
    /// Defines the <see cref="Xuly" />
    /// </summary>
    public partial class Xuly
    {
        /// <summary>
        /// form1 control
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
